### ISSUE TITLE
这尼玛还收费，搞的你开发的，一样，缺那点钱买棺材？

### ISSUE THREAD

**Issue by RomanceLink** [Z39/Lenovo-Y430p-OS-X-Clover-Hotpatch#2]
真是看不惯这种人，以为自己做了什么贡献，恶心，大家加我，免费分享最新y430p，包括wifi

**Comment by Z39** [comment]
老早就在远景论坛发帖接小Y黑果前辈的手维护更新了，我要想靠这个发财，老早就可以这么干了，ok?这个机子已经是老机了，没必要再继续折腾下去了，现在我把什么东西都传在远景和github上了，ReadMe中也说明了。不想说什么，有问题的时候就各种伸手伸嘴艾特，一设置需要打赏就各种恶心，真心累。工作时间忙，没太多时间靠爱发电了，再说一次，这只是给一部分已经打赏过我的机友提供的继续维护更新服务，我没义务去帮所有的机友装上黑果，也没义务一直维护更新下去。PS.据远景的版规，也没在远景发布任何关于打赏的信息。在远景有时间也会继续发教程帖回馈论坛，谢谢！
